steps:
  # 1️⃣ Authenticate with GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials $_CLUSTER_NAME --region $_REGION

  # 2️⃣ Clone Helm Chart Repo
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Clone Helm Charts Repo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://${_GH_TOKEN}@github.com/yohai-wideops/fhenix-cicd-helm.git helm-repo
        cd helm-repo

  # 3️⃣ Apply Backend Helm Chart (Uses Alpine Helm Image)
  - name: 'alpine/helm'
    id: 'Deploy Backend'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd helm-repo/backend
        helm upgrade --install backend . --namespace backend --create-namespace

  # 4️⃣ Apply Frontend Default Helm Chart (Uses Alpine Helm Image)
  - name: 'alpine/helm'
    id: 'Deploy Frontend (Default)'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd helm-repo/frontend-default
        helm upgrade --install frontend-default . --namespace frontend --create-namespace

  # 5️⃣ Apply Frontend HPC Helm Chart (Uses Alpine Helm Image)
  - name: 'alpine/helm'
    id: 'Deploy Frontend (HPC)'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd helm-repo/frontend-hpc
        helm upgrade --install frontend-hpc . --namespace frontend --create-namespace

options:
  logging: CLOUD_LOGGING_ONLY
