steps:
  # 1️⃣ Authenticate with GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials $_CLUSTER_NAME --region $_REGION

  # 2️⃣ Clone Helm chart repo (fhenix-cicd-helm)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Clone Helm Charts Repo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://${_GH_TOKEN}@github.com/yohai-wideops/fhenix-cicd-helm.git helm-repo
        cd helm-repo

  # 3️⃣ Apply Backend Helm Chart
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd helm-repo/backend
        helm upgrade --install backend . --namespace default --create-namespace
        helm upgrade --install backend . --namespace hpc --create-namespace

  # 4️⃣ Apply Frontend Default Helm Chart
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Frontend (Default)'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd helm-repo/frontend-default
        helm upgrade --install frontend-default . --namespace default --create-namespace

  # 5️⃣ Apply Frontend HPC Helm Chart
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Frontend (HPC)'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd helm-repo/frontend-hpc
        helm upgrade --install frontend-hpc . --namespace hpc --create-namespace

options:
  logging: CLOUD_LOGGING_ONLY
