apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-default
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend-default
  template:
    metadata:
      labels:
        app: frontend-default
    spec:
      containers:
        - name: frontend-default
          image: {{ .Values.imageRegistry }}/{{ .Values.image }}:{{ .Values.tag }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
