apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-default
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend-default
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
