{{- define "backend.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.imageRegistry }}/{{ .Values.backend.image }}:{{ .Values.backend.tag }}
          ports:
            - containerPort: {{ .Values.backend.ports.containerPort }}
          env:
            - name: BG_COLOR
              value: "{{ .Values.backend.env.default }}"
{{- end }}

{{- define "frontend.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.default.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.imageRegistry }}/{{ .Values.frontend.default.image }}:{{ .Values.frontend.default.tag }}
          ports:
            - containerPort: {{ .Values.frontend.default.ports.containerPort }}
{{- end }}
